server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:

spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
      include: bus-refresh
