server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

# 网关配置
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: euraka-client
    api-b:
      path: /api-b/**
      serviceId: feign
